### ISSUE TITLE
tracking not accurate 

### ISSUE THREAD

**Issue by miyuki-ts** [RoanH/KeysPerSecond#101]
If i start drawing circles, it will show i am drawing straight lines many of them but where it rotates, it is bad at round or circle movement, if i make short movement, if i make big movement then it will show correct. I also notice on bigger movement, it is not a circle, it is just a 5 angle, as it seems like it cannot do rounds, it also do edges on every moment

![image](https://github.com/RoanH/KeysPerSecond/assets/93956624/6573c29b-098c-4a1b-8803-f3cb00ad511d)

Like this is not an circle at all, it just draw lines but rotate them.

**Comment by RoanH** [comment]
No problem, glad you figured it out!
