### ISSUE TITLE
Keeps running in background after being closed

### ISSUE THREAD

**Issue by Balint817** [RoanH/KeysPerSecond#102]
Title. Just download the new version, started it, then decided I wanna organize my files... So I closed, then tried to move it to a different folder, but it said it was still running. Couldn't find a window or tray icon anywhere so I assume this is a bug.

**Comment by Balint817** [comment]
Only happens when the X is used instead of the "Exit" button

**Comment by RoanH** [comment]
Interesting, thanks for the report! I can reproduce this without any issues and I know what the root cause is, so I hope to get it fixed for the next release.

**Comment by RoanH** [comment]
Actually, that wasn't a very hard fix, so this will be resolved in the next release (v8.10).
