### ISSUE TITLE
README doesn't mention that admin is required for certain apps.

### ISSUE THREAD

**Issue by Balint817** [RoanH/KeysPerSecond#104]
Not really an "issue", but this was the easiest way to let you know. For games that run with elevated priviliges (Genshin, for example), input tracking will only work once you run it as administrator, and I believe that this should at least be mentioned as a possible fix in case somebody encounters this issue and doesn't know how to fix it.

**Comment by RoanH** [comment]
Thanks for the suggestion, that's true yeah, applications can only see key strokes to applications running a lower or equivalent permission level (on Windows anyway). I'll add a note about that to the readme.

**Comment by RoanH** [comment]
Added a new note under the notes section in the readme now.
