### ISSUE TITLE
Auto save results

### ISSUE THREAD

**Issue by henricazottes** [RoanH/KeysPerSecond#18]
Hey it's me again.

I accidentally closed the terminal running the app at the end of the day. As I wanted to know how many keys I typed, it's kind of a fail.

Would it be possible to auto save results every so often ?

**Comment by RoanH** [comment]
Yes this would be possible (and useful).

I already have stats saving implemented anyway, thus adding a few options to call it periodically wouldn't be much of an issue. It should even be possible to save at shutdown (unless it's a sigkill).

This should be implemented together with your other issue in version 8.2.

**Comment by RoanH** [comment]
This is now also implemented and will be released with v8.2.
There is one last small feature I want to try implement for version 8.2, but I expect to release it within a few days from now.
