### ISSUE TITLE
OSU!mania can't register key when using KeysPerSecond

### ISSUE THREAD

**Issue by jkkkj123** [RoanH/KeysPerSecond#19]
Hi, This is great work!

I used KeysPerSecond-v8.2.exe in win10.
I found that OSU! sometimes can't read keys when I play OSU!mania and used KeysPerSecond and OBS. 
This caused that keys I pressed to be judged as a miss.
This interval will occur once every 5-30 seconds.
But I don't understand why was bug happen, maybe it just a case.

Thank you

**Comment by RoanH** [comment]
Hey,

Thank you for the report.

I will try to look into this, although I have limited time at the moment. I'm afraid though that there is a reasonably high chance that I won't be able to figure out what exactly is causing this. I'm first going to attempt to reproduce this. I have gotten a similar report before about beatoraja 2 years ago, but I wasn't ever able to reproduce that case. Another complication is that the actual key handling is done by a library called jnativehook so I have no influence over that part.

Anyway, I hope to be able to figure this one out but it will probably take a long time at the very least :/

**Comment by RoanH** [comment]
Hey, I'll be releasing v8.4 soon which includes a major update to the native key handling. Hopefully it will also fix this issue, though I cannot test that. Either way, I will close this issue for now, if the problem persists in v8.4 please let me know so I can reopen this issue.
