### ISSUE TITLE
Suggestion: Load config from command line argument

### ISSUE THREAD

**Issue by Adrriii** [RoanH/KeysPerSecond#24]
First; amazing program!

Now, loading the config each time i start the program is a bit annoying, i made a script that starts all my streaming tools and what takes the most time is this.

So intead of doing `start KeysPerSecond-v8.2.exe`, then manually clicking config, looking for the file, etc ...
It could simply be `start KeysPerSecond-v8.2.exe C:\pathtofile.cfg` 👌

**Comment by Adrriii** [comment]
Lol don't pay attention, I went in the code to try and add it myself and ... it's already in the program! Everything works fine, thank you :)

**Comment by RoanH** [comment]
:sweat_smile: Thanks

Yeah, this was requested a long time ago, but since it's only mentioned in the readme it gets missed quite often 🙃
