### ISSUE TITLE
Stat Saver

### ISSUE THREAD

**Issue by FappingAngel** [RoanH/KeysPerSecond#25]
Hey, i am trying your program, to see how much I play Osu Mania. In general I liked your Setup with the Keyspresses for each Key, and all Keys in total, but I would have liked it, to save the Statistics automatically. Is there any possible way to Save the Keylogs in the Setup-file itself or have an extra file, which the program overwrites automatically when you close it? I just dont like the Stat saving in a certain interval creating a new File each time.

**Comment by RoanH** [comment]
Overwriting a file and loading the data from that on startup should be possible yeah. I'll look into adding the required functionality for that.

**Comment by RoanH** [comment]
This is now implemented (9d8baf321d0bf34ffed214616216186ecc3f5219) and will be included in the next release (v8.4).
