### ISSUE TITLE
When I press the game the program disappears, what do I do to correct it?

### ISSUE THREAD

**Issue by SamuelRDSOP** [RoanH/KeysPerSecond#26]
I program the keys everything is working and ready to play in the game and the program disappears what do I do?

![Captura de Tela (673)](https://user-images.githubusercontent.com/70699244/92110021-6f98a580-edc0-11ea-8783-54c538f80d77.png)

![Captura de Tela (674)](https://user-images.githubusercontent.com/70699244/92110047-7a533a80-edc0-11ea-9916-7de087c19236.png)

**Comment by RoanH** [comment]
Do you have the `overlay mode` option enabled? As far as I can tell everything should work properly if you have that option enabled.

**Comment by SamuelRDSOP** [comment]
Thanks :)

**Comment by RoanH** [comment]
You're welcome 😄
