### ISSUE TITLE
Added a function to adjust the update cycle of "Total"

### ISSUE THREAD

**Issue by ojh050118** [RoanH/KeysPerSecond#27]
It feels like the update cycle of "Total" is 1 second.
It would be nice if you could update "Total" immediately or set the frequency.

**Comment by RoanH** [comment]
The update frequency of the `total` panel is controlled by the update rate. So if you want it to update faster you can change that setting.

**Comment by RoanH** [comment]
I'm going to close this for now. I hope that my previous comment resolved the issues, if not feel free to reopen this. Immediate global stat panel updates are not something I have on my todo list for the time being. Though I don't rule out that I might implement something like that some day.
