### ISSUE TITLE
showing

### ISSUE THREAD

**Issue by JuicedBird76444** [RoanH/KeysPerSecond#29]
how do i get it to work/ show it on my own thing when doing a game?

**Comment by RoanH** [comment]
In principle it's just a separate window that you can position anywhere you like. If you want to show it on top of the game you are playing then you will need to enable 'overlay mode'. This will attempt to place the KeysPerSecond window on top of any other non-fullscreen windows. If the game you want to overlay is running in fullscreen mode, then overlaying it is not possible, see #28 for the feature request that tracks this. However, depending on the game it might be an option to not run your game in exclusive fullscreen mode. something like full screen windowed should work just fine.

**Comment by RoanH** [comment]
Closing this for now.
