### ISSUE TITLE
Layout body moves when you use arrow keys 

### ISSUE THREAD

**Issue by Kayla** [RoanH/KeysPerSecond#31]
I found a UI bug that messes up when you are configuring stuff. If you use the arrow keys to navigate the UI within Layout, the UI elements move up and down the page. This works for everything in the program and also works in all 4 directions. imgur.com/a/2g8yTN3

Reopening the Layout box resets the position of the elements.

**Comment by RoanH** [comment]
Wait what, I, uh, that looks lovely 😂 I think I know what causes this, but that's a nice find for sure, thanks for reporting it!

**Comment by RoanH** [comment]
This is fixed now, so this will no longer happen in the upcoming v8.5 release. I still love this bug though, so thanks again for reporting the best bug I have ever seen so far 😄.
