### ISSUE TITLE
Suggestion: Allow renaming of cells / removing of cell names.

### ISSUE THREAD

**Issue by Kayla** [RoanH/KeysPerSecond#32]
Just a suggestion. It would be nice to be able to just have numbers in boxes if the layout you choose is intuitive enough. Or, if the number is large, just make the word larger so it doesn't dwarf the size of the abbreviation.

**Comment by RoanH** [comment]
Fair enough, I'll add a rendering mode to only show the the value or the text.

I'm not entirely sure what you mean with the second statement though. Both the text and number are always shown at the largest size that will fit in the panel. I could probably look into limiting the value to be at most the font size of the text and vice versa. Larger numbers would mean that the text can get very small that way though. It'll probably require some experimenting.

**Comment by Kayla** [comment]
I mean manually, so for example if you're at 100,000 key presses you can manually change "TOT" or "#" to "Total Presses" with the freedom of changing the box names.

**Comment by RoanH** [comment]
Ah, seems like I kinda misunderstood. But yeah that makes sense (I already had it on my todo list actually), you can also already do this for key panels. But this is definitely something I plan to implement for the other panels as well.

**Comment by RoanH** [comment]
You'll now be able to change the display name of any panel starting from v8.8 (which should release somewhere next week).
