### ISSUE TITLE
Cause error when use obs to record the screen

### ISSUE THREAD

**Issue by lxymahatma** [RoanH/KeysPerSecond#33]
when using obs to record the software there are some black space around it and when your mouse attached to these zones the obs catches the image that your mouse starts strobing
![image](https://user-images.githubusercontent.com/66151783/123049134-d0699b00-d431-11eb-9e17-39b4069c6e42.png)
![image](https://user-images.githubusercontent.com/66151783/123049186-dfe8e400-d431-11eb-9fcd-d5bf9505a58a.png)

I guess maybe because the java version?
My java version is jdk1.8.0_291

**Comment by RoanH** [comment]
Not really sure what would cause this, I would expect this to be an issue with OBS, but for me OBS does not include any extra black space at all. I also made sure to update to the latest OBS version (27.0.1), but that didn't change anything. Also tried both Java 15 (15.0.1) and Java 8 (1.8.0_151) and both work fine for me. I'm also using a Window capture just like you are an the capture settings make no difference for me. 
![afbeelding](https://user-images.githubusercontent.com/8530896/123132536-23058000-d44f-11eb-81b9-12d401cca6e4.png)

**Comment by RoanH** [comment]
However, regardless of the exact cause, it's probably very unlikely that this is something I can fix. Especially when I can't reproduce it :(

**Comment by lxymahatma** [comment]
![image](https://user-images.githubusercontent.com/66151783/123185087-b5496a80-d4c7-11eb-92a7-2aa2d99570a1.png)
The reason I think the problem is the Java version is that I found out the font of the keyspersecond is not as normal (maybe it's my illusion) I think the text is getting bold but it didn't happen before, until last weekend I updated my java version from Java 8 (1.8.0_131) to Java 8 (1.8.0_291). But I'm not sure about it...

**Comment by lxymahatma** [comment]
Well, I tried to use Java 8 (1.8.0_151) but it didn't fix :(
Maybe I should look for other factors

**Comment by RoanH** [comment]
:/ that's unfortunate, you can try other versions of Java but I doubt that would fix it then. Though, as workaround you might be able to use the `Crop/Pad` filter built into OBS to cut away the extra space.

**Comment by lxymahatma** [comment]
I changed the capture method from Automatic to Windows10 and it fixed, well that's really confusing but finally the problem is solved! Thanks!

**Comment by RoanH** [comment]
Nice! Not sure if I was of much help but I'm glad you managed to figure it out \:)
