### ISSUE TITLE
adapt to other keyboard layouts

### ISSUE THREAD

**Issue by KiteAB** [RoanH/KeysPerSecond#35]
im using arch linux and colemak keyboard layout, there r some small bugs when adding keys, maybe this is java's problem?

**Comment by RoanH** [comment]
I'm not sure what issues you are experiencing, but I doubt they are Java related. All the key handling is done by the [jnativehook](https://github.com/kwhat/jnativehook) library which handles the key events in C. The GitHub page lists the exact requirements for Linux and perhaps you can find an open issue that that describes the problems you are having.

On another note, if you are not already using v8.4 you might want to update as I upgraded jnativehook in this version.

**Comment by KiteAB** [comment]
i updated to v8.4 very early.
in colemak keyboard layout, some keys is different from qwerty.
if i add `z r s d n y o /` (colemak) keys, they still display the qwerty pos `z s d g j o ; /`, this is understandable.
but when i added up arrow, prog added print screen key, thats weird
left arrow -> Alt
right arrow -> Undefined
ik this may a java lib issue, but can u fix it?

**Comment by RoanH** [comment]
Mhm, I'm almost completely certain that is this related to the key handling library I mentioned. So this would be out of my control, however, you can change the display name of keys you've added. The key handling for this is not done using a library but by Java itself. It is possible that you can put proper display names for the keys this way.
