### ISSUE TITLE
"No key's pressed"

### ISSUE THREAD

**Issue by AaronUnknownn** [RoanH/KeysPerSecond#36]
I'm on mac but when I press a key and click save I get a popup that says "No Key's Pressed"

**Comment by RoanH** [comment]
Currently the exact requirements are [Apple OS X 10.5 - 10.12 ](https://github.com/kwhat/jnativehook#software-and-hardware-requirements). I sounds to me like the library responsible for handling key presses in OSX cannot be loaded. But I also do not own any Apple hardware so I cannot do any testing myself.

**Comment by RoanH** [comment]
Going to close this for now since I would need more information to start an investigation.
