### ISSUE TITLE
When pressing second key next counter duplicating

### ISSUE THREAD

**Issue by Planeptunia** [RoanH/KeysPerSecond#38]
When im pressing first key (T) counter is working properly, but when im pressing second key (Y) next counter (Total key presses) is duplicating. Tried it with not only total key presses and every other counter also duplicating itself.
Link to video of issue: https://www.youtube.com/watch?v=n5HP15p_558

**Comment by RoanH** [comment]
Hmm, that looks interesting, I cannot seem to be able to reproduce it though (at least under Windows 10). Can you maybe send a config file that causes this? And maybe any other information you think might be relevant.

**Comment by Planeptunia** [comment]
I figured out what it affected by update rate, in video i tested it on 1000ms but if i make it lower i need to press it quicker to get this glitch, and around 50ms counters started working properly.
also link to cfg: [config.kpsconf3.renamed_because_github.txt](https://github.com/RoanH/KeysPerSecond/files/7026954/config.kpsconf3.renamed_because_github.txt)

**Comment by RoanH** [comment]
Interesting, I'm still rather curious as to what's going on exactly. But without a way to reproduce it myself there isn't much I can do. Presumably it's some specific combination of hardware/software/OS that causes it. If setting the update rate to 50ms is an acceptable solution for you then I guess that works. I might also fix the issue by accident sometime as I change the rendering code quite frequently. Sorry I couldn't be of more help.

**Comment by RoanH** [comment]
I'm going to close this for now hoping a future update to the rendering system will fix this or until someone finds some reliable way to reproduce this.
