### ISSUE TITLE
Remove hotkeys for commands

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#45]
Sometimes the hotkeys conflict with other hotkeys and I want to remove them because personally they are not commonly used.

**Comment by RoanH** [comment]
While currently remove thing the hotkeys is not supported, you can just rebind them to something you'll never hit by accident (<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>]</kbd> or something for example). I'll place being able to remove them completely on my todo list though, but I'm not sure when I'll get around to it.

**Comment by UlyssesZh** [comment]
Got a workaround. Set the key code of the hotkey in a config file as some nonsense key (such as `-100`) and load the config file.

**Comment by RoanH** [comment]
That works as well yeah, if anything that would map to the 100th mouse button. But I doubt there is a mouse with that many buttons and I'm not passing mouse events to the command handling anyway.

**Comment by RoanH** [comment]
The next release (v8.6) will have support for leaving command keys unbound.
