### ISSUE TITLE
Background color opacity bugs the OBS capture 

### ISSUE THREAD

**Issue by SukeSJ** [RoanH/KeysPerSecond#48]
I have no clue if this is just my pc that is stupid or the program not working. I would love to have the background gone but i can't figure out a good color combination to chroma key it and the opacity just makes anything that captures it bug out
https://user-images.githubusercontent.com/67334059/145701118-be06284b-b80b-4558-9641-ded2f6d311b5.mp4

**Comment by RoanH** [comment]
It seems like most capturing software does not support transparent windows (at least not those that I know of). This pretty much only leaves chroma key as an option if you want a truly transparent view. I've seen people that did get a chroma key to work so I know it's possible (possibly requires a specific threshold). Other than that the only way to capture the window with transparency that I know of is doing a screen capture and then cropping that (which would capture the window together with what's behind). The ability to set a custom background is also planned #43 though this is slightly different.
