### ISSUE TITLE
failed to save/load stats

### ISSUE THREAD

**Issue by kid219** [RoanH/KeysPerSecond#51]
(Some sentences were written using a translator)
When I try to "save stats",
it says, 
> Failed to save the statistics!
> Cause: dev.roanh.kps.Key

but total, maximum, average were saved successfully.

and then, if I load that save,
it says,
> Failed to load the statistics!
> Cause: writing aborted; java.io.NotSerializableException: dev.roanh.kes.Key

also total, maximum, average were loaded successfully.

After update to v8.5, when I try to save or load, it always display above contents.

**Comment by RoanH** [comment]
Yikes, that's a pretty big oversight on my part... I will try to get this fixed as soon as possible, though it will likely still take a few weeks before I have time... Stats saving in v8.5 is pretty much completely broken and even if it wasn't, it wouldn't be possible to load a stats file from v8.4 in v8.5... If you want to use the stats saving feature you will need to use v8.4 for now, or wait for v8.6, sorry.

**Comment by frinkifail** [comment]
welp there goes my 8000 keys stat

**Comment by RoanH** [comment]
> welp there goes my 8000 keys stat

The statistics format will be text based in the next release, so as long as you remember the approximate values you can restore it manually.

**Comment by RoanH** [comment]
This is now fully fixed and will work gain in the next release (v8.6).
