### ISSUE TITLE
can't use program

### ISSUE THREAD

**Issue by RuinPoint** [RoanH/KeysPerSecond#53]
hello, i'm korean user. 
A little talk english sorry.
play the "elswrod" game wtih use keyspersencond. but keyspersecond is not play

안녕하세요, 저는 한국 유저입니다.
능숙하지 못한 영어실력 죄송합니다.
Elsword 게임과 keyspersencond를 같이 사용하려 합니다. 그러나 keyspersecond가 실행되지 않습니다.

**Comment by RoanH** [comment]
Hello, unfortunately that is not enough information for me to work with. What is the exact problem you're having? KeysPerSecond runs separately from any game so I assume that even normally it doesn't run? If you're using the runnable Java archive version do you have Java 8 or higher installed?

**Comment by RoanH** [comment]
Closing this for now, feel free to reopen with more details.
