### ISSUE TITLE
Failed to save and load statistics

### ISSUE THREAD

**Issue by Balint837** [RoanH/KeysPerSecond#57]
"Failed to save statistics on exit.
Cause: dev.roanh.kps.Key
Attempt to save again?"

"Failed to load statistics on launch.
Cause: writing aborted; java.io.NotSerializableException: dev.roanh.kps.Key"

The same error is also thrown when trying to load them manually

**Comment by RoanH** [comment]
Version 8.6 has been released and this issue should be resolved. Thanks again for the support!
