### ISSUE TITLE
The key <kbd>[</kbd> is mistakenly shown as the <kbd>(</kbd>

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#60]
The key <kbd>[</kbd> is shown as <kbd>(</kbd> in the interface.
![image](https://user-images.githubusercontent.com/26196187/172993040-574a9882-c541-4734-9813-662e46f2ccd4.png)

**Comment by RoanH** [comment]
Oops, thanks for the report, seems like I mixed those two up, will be fixed in the next release.

**Comment by RoanH** [comment]
This will be fixed in the upcoming v8.7 release.
