### ISSUE TITLE
Do not make shortcuts effective at the start-up configuration 

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#66]
When KeysPerSecond is launched, there is a Window for me to configure it and there is no main GUI. However, if at this interface I hit <kbd>Ctrl</kbd> + <kbd>R</kbd> or <kbd>Ctrl</kbd> + <kbd>Y</kbd>, I will make the main GUI visible, which is not expected.

**Comment by RoanH** [comment]
Oh wow, that's amazing, and quite broken too, thanks for the report. Seems like it varies to what extend this affects various versions, at least it seems like in recent versions <kbd>Ctrl</kbd>+<kbd>R</kbd> is required to be used before <kbd>Ctrl</kbd>+<kbd>Y</kbd> will work. Either way this should not be that hard to fix.

**Comment by RoanH** [comment]
This has been fixed for v8.8, command keys now only become active after launching the main GUI. Thanks again for the report!
