### ISSUE TITLE
stretched on obs

### ISSUE THREAD

**Issue by DaisyD2** [RoanH/KeysPerSecond#68]
Whenever i play osu with it open it becomes stretched on obs, likely due to it being fullscreen, alternatively when i move it to my 2nd monitor it starts to flicker on obs, anyone have a solution?

**Comment by RoanH** [comment]
I haven't personally experienced either of those issues. I'm using a Window capture with the default capture method, it might be worth trying all the capture methods you have available to see if any solve the issue. Technically doing a whole screen capture and then using a filter to crop to just the KPS window would also work but that's a bit of a hacky method. If the capture normally works fine and only has issues when osu! is running in fullscreen then that is a bit weird though.

**Comment by RoanH** [comment]
Going to close this for now.

**Comment by DaisyD2** [comment]
> I haven't personally experienced either of those issues. I'm using a Window capture with the default capture method, it might be worth trying all the capture methods you have available to see if any solve the issue. Technically doing a whole screen capture and then using a filter to crop to just the KPS window would also work but that's a bit of a hacky method. If the capture normally works fine and only has issues when osu! is running in fullscreen then that is a bit weird though.

well i've only tried using it with ffr (windowed only) and osu! and ive really only had issues with osu but i just realized it may have something to do with me having an amd card?  i dont know if thats something youve thought of but ill go ahead and try a couple things you mentioned

**Comment by RoanH** [comment]
Oops, I missed your reply... Your graphics card manufacturer could have something to do with it, but if that is the issue then it's outside of my area of control and more likely to be an OBS or window manager issue. Though that also means there is a chance it could fix itself.
