### ISSUE TITLE
Arrow keys have wrong names

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#71]
- <kbd>Up</kbd> is regarded as <kbd>Print Screen</kbd>;
- <kbd>Left</kbd> is regarded as <kbd>Alt</kbd>;
- <kbd>Down</kbd> is regarded as <kbd>⌘</kbd>;
- <kbd>Right</kbd> is regarded as <kbd>Undefined</kbd>.

The direction keys in the nums pad are fine (if NumLock is off), but the arrow keys cannot trigger (they are regarded as different keys than direction keys in num pad).

I use US keyboard layout. Operating system: Ubuntu 20.04.

Here is [a related bug that I found someone reported on the internet](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/255008).
It seems that it is a problem of keyboard layout.

**Comment by UlyssesZh** [comment]
It seems that this issue is already reported in #35. Closing.

**Comment by RoanH** [comment]
Still thanks for the report! It always helps to have more information on the off chance that I might be able to do something to mitigate the issue.
