### ISSUE TITLE
Glitched GUI

### ISSUE THREAD

**Issue by ChoppyRaccoon94** [RoanH/KeysPerSecond#72]
This is utterly broken. The keybind and setting gui keeps merging with each other and glitching out. While this might not crash the program, it makes it impossible to use on youtube or twitch and just doesn't look good. Everything works fine, its just gui bugs

**Comment by ChoppyRaccoon94** [comment]
im on windows 11 btw

**Comment by RoanH** [comment]
Unfortunately that isn't really enough information for me to work with and not everyone using Windows 11 is running into these issues. I currently also do not have a system running Windows 11 available so this will be hard to debug, even with Windows 11 I would still need my system to actually be affected by this. Though even if I could reproduce it, given that it is a graphical glitch it is likely related to some core of part of Windows so it might not even be something I can fix.

What do you mean with the keybind and settings GUI merging though? Those also aren't really windows you would be having open when using it on YouTube or Twitch.

**Comment by RoanH** [comment]
I'm going to close this for now, feel free to reopen this issue with more details.
