### ISSUE TITLE
How to download the program?

### ISSUE THREAD

**Issue by Exwhy12** [RoanH/KeysPerSecond#75]
im trying to use this in a live stream and dont know how to download it, i'll be fine in putting it into the actual stream, but im not even able to download it

**Comment by Exwhy12** [comment]
oh wait just realized i need java 8 or higher...soooo...okay?

**Comment by RoanH** [comment]
Yup, you need Java 8 or higher, if you do not have Java yet you can [get it here](https://adoptium.net/). You can download KeysperSecond from either the [main page readme](https://github.com/RoanH/KeysPerSecond#downloads) or the [release notes for the latest release](https://github.com/RoanH/KeysPerSecond/releases).

**Comment by RoanH** [comment]
Going to close this for now, feel free to reopen if you things are still unclear.
