### ISSUE TITLE
Do not work in arch with gnome 43.4 (x11&wayland)

### ISSUE THREAD

**Issue by ghost** [RoanH/KeysPerSecond#76]
https://user-images.githubusercontent.com/55263000/232372142-6538289e-019d-4618-b625-33fba64fde7d.mp4

terminal output:[error.log](https://github.com/RoanH/KeysPerSecond/files/11245981/error.log)

**Comment by RoanH** [comment]
Interesting, thank you for the detailed report! I'm not entirely sure _why_ this happens, but it seems like it might not be too hard to fix.

**Comment by cmy47** [comment]
I have encountered some other issues when using Ubuntu 22.04 before, but I am sorry that I am currently using Windows 11 and cannot provide more relevant information: 
1. changing the transparency of the background color will cause it to flicker.
You can watch this video: https://b23.tv/ErGhmBA
2. Unable to open layout interface.

**Comment by RoanH** [comment]
The original issue should be fixed in v8.8.
