### ISSUE TITLE
Weird bug that creates another problem for me.

### ISSUE THREAD

**Issue by T4M1L0S** [RoanH/KeysPerSecond#77]
Hello! Back from my bug that I managed to solve it. Now your suggestion (add position x: y:) makes my display buggy so I can't use it anymore.

But actually, I discovered something interesting (dunno if this is a bug or what), when I load a config in the KPS main menu, it's loaded without any problem, but when I do CTRL+R **_in the main KPS menu_** (which results in reloading the config), the display shows up (at the center of my screen as intended) but now I can move the display, which is a good new for me! (screenshot below)
![Screenshot 2023-04-19 16 48 54](https://user-images.githubusercontent.com/128746612/233114062-5fa87250-53bd-4c68-a124-de686fb4667f.png)

But now the problem I have is that, yes I can now freely move the window, changing it's size etc, but when I right-click on the display (to load my saved statistics), **_the panel menu doesn't show itself_**. I dunno why it is doing that.

I tried with a plain text editor to add "count: X" for each key in the config file to show the count of each of them but it doesn't work (dunno if I edited the file correctly via the plain text editor tho).

I also tried to use the option that automatically loads a .kpsstats file **_before_** clicking "OK" on the main KPS menu, but when I do the bug it shows 0 for everything.

Although, when I said that doing CTRL+R shows the display, it shows itself yes but the main KPS menu is still here too (as the screenshot above shows). 

So even if the display was shown, I tried clicking "OK" on the main KPS menu and it shows the display (with the window bar to move it) but the auto-load stats option still doesn't work.

I don't know what you think about that but: is it possible to make CTRL+R not reset the stats when I load the config (which has the auto-load stats file option) ?

Edit: It seems that UlyssesZh discovered that bug too. So that means if you fix it. I wouldn't be able anymore to get a display with a window bar thingy. (because when I load a config and click "OK" as intended normally, to me it shows the display without the window bar thingy and as you know I can't move it because idk (and as I've said at the beginning, your suggestion makes my display buggy now). So I guess I can't use KPS properly now.

**Comment by RoanH** [comment]
Huh, yeah, you certainly managed to get it into some interesting but not really intended state. I intentionally hide the top bar because it doesn't really fit the theme. I wonder if chromebooks just can't deal with borderless windows... (seems to be the case actually) The only way to set stats is via a stats file, but yeah, those only get applied later on.

It's a little weird, but I can just add in a borderless/windowed toggle for the top bar (which chromeOS seems to require apparently). It doesn't really look all that nice and I need to check if it conflicts with anything else, but if not I might end up adding it.

**Comment by T4M1L0S** [comment]
oops. my bad. didn't mean to close it.

**Comment by RoanH** [comment]
I will add an option to add the window frame yeah, unless it causes issues in some other part of the program, probably it'll be fine though.

**Comment by T4M1L0S** [comment]
ok, thanks for your help. I dunno when you'll release the v8.8 with everything you need to fix and etc but I'm patient. ;)

**Comment by RoanH** [comment]
Hey, I have added a `Windowed mode` toggle to v8.8, so I'll be closing this issue (release should be out later this week). 

The setting will be at the bottom of the options on the initial configuration screen. Assuming your patience managed to last 8 months at least 😅, and if not I hope it'll help some future chromebook user.

**Comment by T4M1L0S** [comment]
Glad to see you've fixed my issue for KPS v8.8, indeed I've waited for many months but I'm sure it'll be worth all of my patience I've given to you! ;)

Thanks for your help RoanH! ^-^
