### ISSUE TITLE
Latest version (8.7) doesn't run on Windows 11 but worked earlier

### ISSUE THREAD

**Issue by Imaproshaman** [RoanH/KeysPerSecond#78]
I tried reinstalling but it just doesn't open now. I didn't do anything recently. Nothing pops up so I can't figure out what the issue is. I also tried the previous version (8.6) but the same issue exists.

**Comment by RoanH** [comment]
Thank you for the report. Can you check if you have any additional information available when running via command line (cmd or PowerShell) with: `java -jar KeysPerSecond.exe`

Most likely there should be some kind of error visible there and probably that will have enough information for me to figure out the cause.

**Comment by Imaproshaman** [comment]
I fixed it by reinstalling Java, so the error was on my end. So it's all good.

**Comment by RoanH** [comment]
Awesome! Thanks for letting me know.
