### ISSUE TITLE
Keyboard minimizes unintentionally

### ISSUE THREAD

**Issue by Zielin555** [RoanH/KeysPerSecond#82]
Basically i added all of the keyboard buttons to my layout and now it just minimizes when i click on another window. I tried to use Powertoys to force the app to be on top, but then it doesn't show which buttons have been pressed. (Everything works normally when there's only a couple buttons).

**Comment by RoanH** [comment]
You shouldn't need an external application to force the application to always be on top, the built in overlay mode also toggles the always-on-top flag. Though I'm unsure if that's related to your main issue. Could you send your configuration file so I can try to reproduce the issue to investigate?

**Comment by RoanH** [comment]
I can't really do anything without your configuration file, so I'm going to close this for now. Feel free to reopen this issue with your configuration file.
