### ISSUE TITLE
The program doesn't launch at all

### ISSUE THREAD

**Issue by chicco-carone** [RoanH/KeysPerSecond#83]
After downloading the latest java release for the program i tried to launch it with java 8 and 20 and it always gave me this error `Error: Could not find or load main class .jar` even with sudo. Os is Arch Linux with kde.

https://github.com/RoanH/KeysPerSecond/assets/66080458/724a4817-1e9a-4803-be60-a0a55c47b04c

**Comment by RoanH** [comment]
Hello, you have a small typo in the command you're using, the command line flag to pass a JAR is `-jar` not `.jar.` Now it's looking for a non-existent file named `.jar` and passing `KeysPerSecond-v8.7.jar` as a program argument.

This should work:
```sh
java -jar KeysPerSecond-v8.7.jar
```

**Comment by chicco-carone** [comment]
Thanks i really didn't notice it. It would be great if in the release there would be a .appimage for linux instead of only a jar file.

**Comment by RoanH** [comment]
Fair, I have more release formats on my todo list already, but haven't really had the time to properly figure things out. I'll add appimage to the list of formats to look into though.
