### ISSUE TITLE
Suggestion: Allow Renaming Text in Cells

### ISSUE THREAD

**Issue by CATuff** [RoanH/KeysPerSecond#84]
I mean, if I use many buttons for very complex operations, it would be best for me to replace the text displayed on the keyboard with the functionality of this button in the game.

(I'm from China and I can't speak English well. I'm sorry if that's odd.)

**Comment by RoanH** [comment]
Hello, you can already do this for regular keys (though I agree it is not super intuitive). You can double click and edit the display text in the `Add key` dialog:
![image](https://github.com/RoanH/KeysPerSecond/assets/8530896/bf15fa57-3599-4b5f-afd9-9f034a3bffaf)

I'll probably try to make this a bit more intuitive in some future release, but the functionality is present.

**Comment by CATuff** [comment]
thank you so much ; _ ;

**Comment by RoanH** [comment]
Glad that resolved your issue!
