### ISSUE TITLE
Auto Reset Issue

### ISSUE THREAD

**Issue by PeterTKL** [RoanH/KeysPerSecond#85]
I don't know why my stat auto reset when it reach to 100k press, I tried so much way like change the layout and something I don't really remember, but it still reset when it reached 100k, Hope you can read this comment! By the way, your KPS good

**Comment by RoanH** [comment]
Interesting issue, it shouldn't be auto resetting like that and I've seen counters with over 100k hits before.

Gave it a try myself and I managed to get past 100k without any issues.
![image](https://github.com/RoanH/KeysPerSecond/assets/8530896/cbae97f0-210e-48a9-a0e9-4a8b4e1b3245)

Do you perhaps have any other relevant information?

**Comment by RoanH** [comment]
Also note that there is a keybind to reset all counters <kbd>Ctrl</kbd> + <kbd>P</kbd>, but from your message it doesn't sound like you're hitting that accidentally.

**Comment by RoanH** [comment]
Going to close this for now as I need more information to be able to reproduce it. Feel free to reopen this issue with more information at a later date.
