### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by capticka** [RoanH/KeysPerSecond#87]
I set Total to be visible in the general settings.
But **_avg, not tot_**, is shown in the layout settings.
(V 8.7)

**Comment by RoanH** [comment]
Yikes, thank you for reporting this. It seem like besides the name being wrong it does still control the correct panel... but yeah I'll fix this for the next release.

**Comment by RoanH** [comment]
Fortunately, this wasn't very hard to fix and the fix will be released in version v8.8. Thanks again for the report.

**Comment by capticka** [comment]
Thank you.
