### ISSUE TITLE
Minimize tray icon, Load last config file on launch

### ISSUE THREAD

**Issue by Atsilut** [RoanH/KeysPerSecond#89]
I've been used this about 1 week and it's pretty great as others suck.
But what makes me feel annoying is, there is no option to minimize to tray icon.
I can easily find about statistics but, config is nowehre. I really hope there is 'Load last config file on launch' option. 
Can you work for these? I can't find better than yours at least now. It's gonna be perfect bro

**Comment by RoanH** [comment]
Hi, support for the system tray is an interesting idea, I'll place that on the todo list to look into.

There are currently [a few methods](https://github.com/RoanH/KeysPerSecond/wiki) you can use to skip loading a config manually. I do intend to add more in the future, but I am still trying to find a good balance between not storing data in random places on the user's computer and convenience.

**Comment by RoanH** [comment]
Thanks to @DeSu0556 support for minimising the program to the system tray will be available starting from v8.8 (to be released somewhere this week).

**Comment by RoanH** [comment]
Starting from v8.8 (to be released later this week) there is an option to configure a default configuration that the program automatically loads on startup.
