### ISSUE TITLE
Bad initial position for some monitor layouts

### ISSUE THREAD

**Issue by UlyssesZh** [RoanH/KeysPerSecond#94]
My monitor layout is like this:
![image](https://github.com/RoanH/KeysPerSecond/assets/26196187/745e16ca-43fc-4162-a5cc-5854ba4a17dc)
When the UI of KPS initializes its position to (0,0), I cannot see it because my monitor does not cover there. It spent me quite a while figuring out how to get that window in my viewport.

Would it be possible to have something else as the default position? I think the center of the screen would be better.

**Comment by RoanH** [comment]
Interesting bug. I'm kind of surprised Java even uses (0,0) as the default for setups like that. I can definitely just call the command to center the frame though, so I'll start doing that, though now I wonder if that one could ever put it offscreen... Though I guess I'll just do center for now, if it ever goes off-screen again I'll manually compute the corner of a display and use that.

Thanks for yet another report! I'm currently planning to do another release either tomorrow or this weekend to fix some bugs and add a few more features.

**Comment by RoanH** [comment]
Thanks to @efojug this will be fixed in the next release.

**Comment by EnderiteFox** [comment]
The same thing is currently happening to me

Here is my monitor layout:
![Image](https://github.com/user-attachments/assets/4db02a00-a0ea-47f4-a8a8-0849e06afa33)

I have tried to save the config with kps at the top left of the right monitor, and at the center of the right monitor, but the window still loads at the top of the left monitor, where it is unreachable

Version 8.9, Kubuntu 24.10, KDE Plasma 6.1.5

**Comment by RoanH** [comment]
Interesting, did you check if the position values saved in the config make sense (frame.x and frame.y)? And if you load a config without any saved position does the window still end up off screen?

**Comment by EnderiteFox** [comment]
Yes, the frame position is correct in the config.

And I just tested it, loading a config with no saved position makes it start correctly at the center of the screen
